version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1 
      - HOSTNAME=localhost
    networks:
      - localstack-net
    volumes:
      - ./data:/tmp/localstack
  

networks:
  localstack-net:
